### ISSUE TITLE
RuntimeError: mat1 and mat2 shapes cannot be multiplied (8x4 and 16x80)

### ISSUE THREAD

**Issue by lsy1973** [ispamm/hTorch#14]
Hi,
I am very interested in your work and thanks for what you have done
I encountered a problem when I tried to run your sample code in the file "notebooks/basic.ipynb" line
input:
```
import torch
from torch import nn
from htorch import quaternion
from htorch.layers import QLinear
# Simple model with two quaternion-valued dense layers, and a split ReLU (ReLU applied on each component separately)
model = nn.Sequential(
    QLinear(4, 20, bias=True),
    nn.ReLU(),
    QLinear(20, 1)
)
x = quaternion.QuaternionTensor(torch.rand(2, 4, 4))
print(model(x))
```
out put:
```Traceback (most recent call last):
  File "D:/code-study/hTorch-main/notebooks/vgew.py", line 13, in <module>
    print(model(x))
  File "C:\anaconda3\envs\pytorch_qua_env\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\anaconda3\envs\pytorch_qua_env\lib\site-packages\torch\nn\modules\container.py", line 141, in forward
    input = module(input)
  File "C:\anaconda3\envs\pytorch_qua_env\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\code-study\hTorch-main\htorch\layers.py", line 268, in forward
    return Q(F.linear(x, weight.t(), self.bias))
  File "D:\code-study\hTorch-main\htorch\quaternion.py", line 543, in __torch_function__
    return func(*args, **kwargs)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (8x4 and 16x80)```


![image](https://user-images.githubusercontent.com/80167832/170857782-16bbc3d0-8b9e-4093-a89c-a99396ec0c4b.png)

![image](https://user-images.githubusercontent.com/80167832/170857792-b8d922b2-2073-4513-801b-ba2cedabc5b4.png)
I've installed requirements.txt, still not working, 
Can you answer for me, thank you!

**Comment by lsy1973** [comment]
here are the screenshots, thanks!
![image](https://user-images.githubusercontent.com/80167832/170857782-16bbc3d0-8b9e-4093-a89c-a99396ec0c4b.png)
![image](https://user-images.githubusercontent.com/80167832/170857792-b8d922b2-2073-4513-801b-ba2cedabc5b4.png)
