### ISSUE TITLE
Dimension Mismatch error for QConv1d

### ISSUE THREAD

**Issue by souravmpi** [ispamm/hTorch#7]
Hi,
I was looking at your great work on this repo on QNNs. I am facing an issue, and would request your help.

So, for each input data point, I have 4 different channels (input mechanisms), and each channel provides 1024 features (array of size 1024) for the data. Thus for training we have an input_data of size `(64 * 4 * 1024) [batch_size=64]`. The goal is classification into `num_class`, using a Quaternion Conv1D. Please find a snapshot of the code below.
```
kernel = 1
out_chn = 4
out_conv = ((1024 - 1 * (kernel - 1) - 1)) + 1
out_pool = ((out_conv - 1 * (kernel - 1) - 1)) + 1
inp_lin = out_pool*out_chn
#
## Model Definition
model_QNN = torch.nn.Sequential(
        layers.QConv1d(in_channels=1, out_channels=out_chn, kernel_size=kernel, stride=1, bias=True),
        torch.nn.ReLU(),
        torch.nn.MaxPool1d(kernel_size=kernel, stride=1),
        torch.nn.Flatten(),
        layers.QLinear(inp_lin, num_class),
        layers.QuaternionToReal(num_class)
        )
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model_QNN.parameters())
model_QNN.cuda()
criterion.cuda()
#
## Training Loop
for epoch in range(5):
    for i, (inputs, targets) in enumerate(train_dl):
        yhat = model_QNN(inputs.cuda())
        loss = criterion(yhat.cuda(),targets.cuda())
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
```

However, the above throws the following error during training:
```
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "/QNN/hTorch/q_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/QNN/hTorch/q_env/lib/python3.6/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/QNN/hTorch/q_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/QNN/hTorch/htorch/layers.py", line 92, in forward
    self.padding, self.dilation, self.groups))
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [16, 4, 1, 1], but got 3-dimensional input of size [64, 4, 1024] instead
```

What am I doing wrong here? Thanks in advance.

**Comment by giorgiozannini** [comment]
Thanks a lot for checking out our work!
There was an error on our end (`QConv1d` was returning a 4 dimensional weight instead of a 3 dimensional one, thanks for making us notice it!) and I think some misunderstanding on the shapes. 
Please find below an example of your code slightly revisited:

```import importlib
from htorch import layers
import torch
import torch.nn as nn
import torch.nn.functional as F

class Dataset(torch.utils.data.Dataset):
    def __init__(self, data, labels):
          self.labels = labels
          self.data = data

    def __len__(self):
          return len(self.data)

    def __getitem__(self, index):
          x = self.data[index]
          y = self.labels[index]
          return x, y

batch_size = 3
width = 20

data = torch.rand(100, 4, width)
labels = torch.randint(2, size=(100,))
train = Dataset(data, labels)
train_dl = torch.utils.data.DataLoader(train, batch_size=batch_size)
num_class = 2

kernel = 1
out_chn = 4
out_conv = 4*out_chn*batch_size*width
out_pool = out_conv
inp_lin = out_pool//batch_size // 4 


model_QNN = torch.nn.Sequential(
        layers.QConv1d(in_channels=1, out_channels=out_chn, kernel_size=kernel, stride=1, bias=True),
        torch.nn.ReLU(),
        torch.nn.MaxPool1d(kernel_size=kernel, stride=1),
        torch.nn.Flatten(),
        layers.QLinear(inp_lin, num_class),
        layers.QuaternionToReal(num_class)
        )

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model_QNN.parameters())
model_QNN.cuda()
criterion.cuda()


## Training Loop
for epoch in range(5):
    for i, (inputs, targets) in enumerate(train_dl):
        yhat = model_QNN(inputs.cuda())
        loss = criterion(yhat.cuda(),targets.cuda())
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
```

We have pushed the fix! If anything does not sound quite right or have any other doubt please do not hesitate and let us know!

**Comment by souravmpi** [comment]
Hi.. 
Thanks a lot! Yes, the updated code fixes the problem. 
Also, many thanks for correcting the shape of the ConvNN in the code.

Just, one question - if I change the number of kernel, then should `out_conv=4*out_chn*batch_size*(width-kernel+1)` be used, or there needs to be other changes?

**Comment by giorgiozannini** [comment]
In your code the kernel size for both the `QConv1d` ad the `MaxPool1d` are regulated by `kernel` so if the max pool had no effect on the `width` that is returned before the `QLinear` then your formula is correct! (if we do not change padding, dilation etc...). In this case if you were to put `kernel=2` you would have first `width-1` after the conv (since there is no padding) and then `(width -1) - 1` after the pool (again because of no padding). But you already figured this out then yes you should have no problems running the code!

**Comment by giorgiozannini** [comment]
I'm sorry just a small correction: the output width for both the maxpool1d and the conv1d operations is given by the formula
```
floor((width + 2*padding - dilation*(kernel_size-1) - 1)/stride + 1)
```
as written on Pytorch's official website.

**Comment by souravmpi** [comment]
Thanks a lot!! Yes, you are correct - now the dimensions and shapes are all sorted! :)

One more question in this respect:
I was also trying out an simple MLP classifier.

As usual we have the data of size `64*4*1024`. And now I am classifying using these features:
1. I flatten the input data from the 4 channels (simply append them) to get `inp_len = 4*1024`
```
        dataset = TensorDataset(train_data, train_labl)
        train_dl = DataLoader(dataset, batch_size=64, shuffle=True)
        inp_len = 4*1024
        model_MLP = nn.Sequential(
                nn.Linear(inp_len,1024),
                nn.ReLU(),
                nn.Linear(1024,num_class),
                )
        criterion = nn.CrossEntropyLoss()
        optimizer = torch.optim.Adam(model_MLP.parameters())
        model_MLP.cuda()
        criterion.cuda()
        #
        for epoch in range(50):
            for i, (inputs, targets) in enumerate(train_dl):
                yhat = model_MLP(inputs.cuda())
                loss = criterion(yhat.cuda(),targets.cuda())
                optimizer.zero_grad()
                loss.backward()
                optimizer.step()
```
2. Now I want to use a `QLinear` on the same data. I tried like this:
```
        dataset = TensorDataset(train_data, train_labl)
        train_dl = DataLoader(dataset, batch_size=64, shuffle=True)
        #
        inp_len = 4*1024 # Or maybe it should be 1024 for QNN
        #
        model_MLP = nn.Sequential(
                nn.Linear(inp_len,1024),
                nn.ReLU(),
                nn.Linear(1024,num_class),
                )
        model_QNN = utils.convert_to_quaternion(model_MLP)
        criterion = nn.CrossEntropyLoss()
        optimizer = torch.optim.Adam(model_QNN.parameters())
        model_QNN.cuda()
        criterion.cuda()
        for epoch in range(50):
            for i, (inputs, targets) in enumerate(train_dl):
                yhat = model_QNN(inputs.cuda())
                loss = criterion(yhat.cuda(),targets.cuda())
                optimizer.zero_grad()
                loss.backward()
                optimizer.step()
```
The training data is properly formatted `64*4096` for the MLP and `64*4*1024` for the QNN. This throws the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "/QNN/hTorch/q_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/QNN/hTorch/q_env/lib/python3.6/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/QNN/hTorch/q_env/lib/python3.6/site-packages/torch/fx/graph_module.py", line 513, in wrapped_call
    raise e.with_traceback(None)
TypeError: chunk() missing 1 required positional arguments: "chunks"
```
I know there is some mistake in my code. Can you please help?

**Comment by giorgiozannini** [comment]
I'm sorry i cannot exactly reproduce the error (I guess it might be some difference in the data?). This is the code I used and it works fine:
```
from htorch import layers, quaternion, utils
import torch
import torch.nn as nn
import torch.nn.functional as F

class Dataset(torch.utils.data.Dataset):
    def __init__(self, data, labels):
          self.labels = labels
          self.data = data

    def __len__(self):
          return len(self.data)

    def __getitem__(self, index):
          x = self.data[index]
          y = self.labels[index]
          return x, y

batch_size=6
width = 1024

data = torch.rand(100, 4*width)
labels = torch.randint(2, size=(100,))
train = Dataset(data, labels)
train_dl = torch.utils.data.DataLoader(train, batch_size=batch_size, drop_last=True)
num_class = 2
inp_len = 4*1024 # Or maybe it should be 1024 for QNN

model_MLP = nn.Sequential(
        nn.Linear(inp_len,1024),
        nn.ReLU(),
        nn.Linear(1024,num_class),
        )

model_QNN = utils.convert_to_quaternion(model_MLP)
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model_QNN.parameters())
model_QNN.cuda()
criterion.cuda()
for epoch in range(50):
    for i, (inputs, targets) in enumerate(train_dl):
        yhat = model_QNN(inputs.cuda())
        loss = criterion(yhat.cuda(),targets.cuda())
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
```

Let me know if I'm missing something!

**Comment by giorgiozannini** [comment]
only a small note: it is advisable to convert your inputs to the quaternion format with `QuaternionTensor`. The nets might work anyway but it is still better to explicitly convert it before feeding it to the network.

**Comment by souravmpi** [comment]
Perfect! I had a problem with the input shape for the `QLinear` - all sorted now. Thanks a lot for your help! 
Please keep up your great work on this library. :)

**Comment by giorgiozannini** [comment]
Thanks a lot! we will keep working on it 👍🏻
